# Generated by Django 4.1.3 on 2022-11-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='QnaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('imageurl', models.TextField(null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('like', models.PositiveIntegerField(default=0)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.usermodel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QnaCommentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('to', models.TextField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.qnamodel')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.usermodel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('imageurl', models.TextField(null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('like', models.PositiveIntegerField(default=0)),
                ('list', models.TextField()),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.usermodel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MainCommentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('to', models.TextField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.mainmodel')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.usermodel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
