# Generated by Django 4.1.3 on 2022-11-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_usermodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincommentmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mainmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qnacommentmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qnamodel',
            name='email',
        ),
        migrations.AddField(
            model_name='maincommentmodel',
            name='uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qnacommentmodel',
            name='uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qnamodel',
            name='uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='imageurl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(default='', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
