# Generated by Django 4.1.3 on 2022-11-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_usermodel_options_usermodel_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='imageurl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
    ]
