# Generated by Django 4.1.3 on 2022-11-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_usermodel_email_alter_usermodel_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='list',
            field=models.TextField(default='', null=True),
        ),
    ]
