# Generated by Django 4.1.3 on 2022-11-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_usermodel_token_alter_maincommentmodel_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincommentmodel',
            name='uid',
        ),
    ]
