# Generated by Django 4.1.3 on 2022-11-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_maincommentmodel_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmodel',
            name='uid',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
