# Generated by Django 4.1.3 on 2022-11-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_maincommentmodel_to_alter_mainmodel_imageurl_and_more'),
        ('community', '0009_remove_mainmodel_uid_usermodel_notification'),
    ]

    operations = [
    ]
