# Generated by Django 4.1.3 on 2022-11-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_merge_20221125_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincommentmodel',
            name='to',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='list',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='imageurl',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
