# Generated by Django 4.1.3 on 2022-11-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_maincommentmodel_to_alter_mainmodel_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainModelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_user', models.IntegerField()),
                ('date', models.TextField()),
                ('title', models.TextField()),
                ('imageurl', models.TextField()),
                ('count', models.IntegerField()),
                ('like', models.IntegerField()),
            ],
        ),
    ]
