# Generated by Django 4.1.3 on 2022-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_rename_count_mainmodel_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodelview',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
