# Generated by Django 4.1.3 on 2022-11-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_mainmodelview_nickname_mainmodelview_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainModelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(null=True)),
                ('parent_user', models.IntegerField()),
                ('nickname', models.TextField(default='', null=True)),
                ('user_url', models.TextField(default='', null=True)),
                ('date', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('imageurl', models.TextField()),
                ('view', models.IntegerField(default=0)),
                ('like', models.IntegerField()),
                ('list', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='mainmodel',
            options={'ordering': ['date']},
        ),
    ]
