# Generated by Django 4.1.3 on 2022-11-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_mainmodeldetail_alter_mainmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincommentmodel',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='mainmodeldetail',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.maincommentmodel'),
        ),
        migrations.AddField(
            model_name='mainmodelview',
            name='user_image',
            field=models.TextField(default=''),
        ),
    ]
