# Generated by Django 4.1.3 on 2022-11-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_remove_mainmodeldetail_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodeldetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
