# Generated by Django 4.1.3 on 2022-11-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_alter_mainmodeldetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmodeldetail',
            name='comment',
        ),
        migrations.AlterField(
            model_name='mainmodeldetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
