# Generated by Django 4.1.3 on 2022-11-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_remove_mainmodeldetail_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincommentmodel',
            name='to',
        ),
        migrations.AddField(
            model_name='mainmodeldetail',
            name='comment',
            field=models.ManyToManyField(to='community.maincommentmodel'),
        ),
    ]
