# Generated by Django 4.1.3 on 2022-11-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_remove_maincommentmodel_to_mainmodeldetail_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='comment',
            field=models.ManyToManyField(to='community.maincommentmodel'),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='nickname',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='user_url',
            field=models.TextField(default='', null=True),
        ),
    ]
