# Generated by Django 4.1.3 on 2022-11-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_mainmodel_comment_mainmodel_nickname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainModelDetail',
        ),
    ]
