# Generated by Django 4.1.3 on 2022-12-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_maincommentmodel_nickname_maincommentmodel_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincommentmodel',
            name='to_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_id', to='community.usermodel'),
        ),
    ]
