# Generated by Django 4.1.3 on 2022-12-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_maincommentmodel_to_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincommentmodel',
            name='to_id',
        ),
    ]
