# Generated by Django 4.1.3 on 2022-12-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_remove_maincommentmodel_to_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincommentmodel',
            name='to_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maincommentmodel',
            name='to_nickname',
            field=models.TextField(default=''),
        ),
    ]
