# Generated by Django 4.1.3 on 2022-12-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_maincommentmodel_to_id_maincommentmodel_to_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCommentModelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('date', models.TextField()),
                ('parent_id', models.IntegerField()),
                ('parent_user', models.IntegerField()),
                ('body', models.TextField()),
                ('nickname', models.TextField(default='')),
                ('user_url', models.TextField(default='')),
                ('to_id', models.IntegerField(default=0)),
                ('to_nickname', models.TextField(default='')),
            ],
        ),
    ]
