# Generated by Django 4.1.3 on 2022-12-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_maincommentmodelview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCommentModelView',
        ),
    ]
