# Generated by Django 4.1.3 on 2022-12-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_delete_maincommentmodelview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmodel',
            name='comment',
        ),
    ]
