# Generated by Django 4.1.3 on 2022-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0034_remove_mainmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='commentcount',
            field=models.IntegerField(default=0),
        ),
    ]
