# Generated by Django 4.1.3 on 2022-12-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0036_mainmodel_imageurlcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmodel',
            name='imageurlcount',
        ),
        migrations.AddField(
            model_name='mainmodelview',
            name='imageurlcount',
            field=models.IntegerField(default=0),
        ),
    ]
