# Generated by Django 4.1.3 on 2022-12-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0037_remove_mainmodel_imageurlcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
